name: Pull Request Lint

on:
  pull_request:
    # By default, a workflow only runs when a pull_request's activity type is opened, synchronize, or reopened. We
    # explicity override here so that PR titles are re-linted when the PR text content is edited.
    #
    # Possible values: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    # renovate PR titles don't follow our convention; therefore, exclude them
    if: startsWith(github.head_ref, 'renovate/') != true
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const regex = /^\[(CU-.+|[nN][oO][cC][aA][rR][dD]|[wW][iI][pP])\] .+/;
            const pr = context.payload.pull_request.number;

            if (!regex.test(title)) {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr,
                event: 'REQUEST_CHANGES',
                body: `Pull request title doesn't conform regex: \`${regex}\`! <br /> More info on this: https://collab.namecheap.net/display/CT/Working+together`
              });
              return;
            }

            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr,
            });

            for (const review of reviews.data) {
              if (review.state === 'CHANGES_REQUESTED' && review.user.type === 'Bot') {
                await github.rest.pulls.dismissReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr,
                  review_id: review.id,
                  message: 'PR title now matches the required format.'
                });
              }
            }
